import Image from "next/image";
import Link from "next/link";
import { SiGmail, SiInstagram, SiWhatsapp } from "react-icons/si";
import { ExperiencesSection, ContactSection } from "./components/home/interactive-sections";
import { InvitationIntro } from "./components/home/invitation-intro";
import "./components/home/invitation-intro.css";
import { siteConfig } from "./site-config";

type Project={number:string;category:string;name:string;className:string;detail:string;video?:string;image?:string};
const projects:Project[]=[
{number:"01",category:"Projeto real / Convite interativo",name:"CONVITE K2",className:"real",detail:"Uma prévia real de convite online interativo criada pela K2 Tech.",video:"/videos/convite-interativo-k2-preview.mp4"},
{number:"02",category:"Conceito / Debutante",name:"JULIA 15",className:"debutante",detail:"Uma experiência digital para anunciar a celebração, compartilhar informações e confirmar presenças.",image:"/images/projects/debutante-julia-v3.png"},
{number:"03",category:"Conceito / Casamento",name:"MAYA & CAIO",className:"wedding",detail:"Um convite elegante e interativo para levar a história do casal até cada convidado.",image:"/images/projects/casamento-maya-caio-v2.png"},
{number:"04",category:"Conceito / Infantil",name:"MIGUEL 06",className:"kids",detail:"Um convite divertido para uma festa infantil começar com brincadeira desde o celular.",image:"/images/projects/infantil-miguel.png"},
{number:"05",category:"Conceito / Chá revelação",name:"BABY LUNA",className:"reveal",detail:"Informações, confirmação e expectativa reunidas em uma experiência delicada e especial.",image:"/images/projects/cha-revelacao-luna-v2.png"},
{number:"06",category:"Conceito / Evento corporativo",name:"IDEA SUMMIT",className:"corporate",detail:"Um convite de alto impacto para conectar convidados à energia de um grande evento.",image:"/images/projects/idea-summit.png"}];
const services=[["01","Convites interativos","Uma experiência feita sob medida com confirmações, localização, cronograma e a personalidade do seu evento."],["02","Sites que posicionam","Presenças digitais rápidas, bonitas e estratégicas para o seu negócio ser encontrado e escolhido."],["03","Soluções sob medida","Projetos digitais que resolvem o que planilhas e processos manuais já não conseguem acompanhar."]];
function whatsappLink(message:string){return `https://wa.me/${siteConfig.whatsappNumber}?text=${encodeURIComponent(message)}`}
function Arrow({diagonal=false}:{diagonal?:boolean}){return <span className={diagonal?"arrow diagonal":"arrow"}>↗</span>}
function K2Mark(){return <span className="official-logo"><Image src="/images/k2-tech-logo-transparent-v2.png" alt="K2 Tech" fill sizes="160px" priority/></span>}

export default function Home(){return <main>
<InvitationIntro/>
<header className="site-header container"><a className="brand" href="#inicio" aria-label="K2 Tech, início"><K2Mark/></a><nav className="desktop-nav" aria-label="Navegação principal"><a href="#sobre">Sobre</a><a href="#projetos">Projetos</a><a href="#avaliacoes">Experiências</a><a href="#servicos">Serviços</a><a href="#contato">Contato</a></nav><a className="header-cta" href={siteConfig.whatsappUrl} target="_blank" rel="noopener noreferrer">Falar no WhatsApp <Arrow/></a><details className="mobile-nav"><summary aria-label="Abrir menu"><span/><span/></summary><div><a href="#sobre">Sobre</a><a href="#projetos">Projetos</a><a href="#avaliacoes">Experiências</a><a href="#servicos">Serviços</a><a href="#contato">Contato</a><a href={siteConfig.whatsappUrl} target="_blank" rel="noopener noreferrer">Falar no WhatsApp</a></div></details></header>
<section id="inicio" className="hero container"><div className="hero-copy reveal"><p className="eyebrow"><span/> EXPERIÊNCIAS DIGITAIS QUE MARCAM</p><h1>Seu evento<br/>começa no<br/><em>primeiro clique.</em></h1><p className="hero-text">Convites online interativos que encantam seus convidados, organizam cada detalhe e transformam expectativa em experiência.</p><div className="hero-actions"><a className="button button-whatsapp" href={siteConfig.whatsappUrl} target="_blank" rel="noopener noreferrer">Falar no WhatsApp <Arrow/></a><a className="text-link" href="#projetos">Ver experiências <span>↓</span></a></div></div><div className="hero-visual reveal" aria-label="Exemplo de convite digital interativo"><div className="visual-note"><span>DESIGN + TECNOLOGIA</span><i/></div><div className="tech-ring ring-one"/><div className="tech-ring ring-two"/><div className="network-lines" aria-hidden="true"><i/><i/><i/><i/><i/></div><div className="invite-device"><div className="device-top"><span>K2 TECH</span><i>●</i></div><div className="device-content"><p>VOCÊ ESTÁ CONVIDADO</p><h3>LIA<br/><em>&amp; CAIO</em></h3><div className="device-date">23 · AGOSTO · 2026</div><span className="device-button">CONFIRMAR PRESENÇA <Arrow/></span></div><div className="device-footer"><span>⌁</span><b>EXPERIÊNCIA DIGITAL INTERATIVA</b></div></div><div className="floating-tag tag-one">convites<br/>interativos</div><div className="floating-tag tag-two">K2®</div></div></section>
<section id="sobre" className="intro container section-space"><div className="section-label"><span>01</span><i/> SOBRE A K2 TECH</div><div className="intro-grid"><h2>Um convite pode ser<br/><em>muito mais.</em></h2><div className="intro-content"><p className="lead">A K2 Tech transforma momentos importantes em experiências digitais memoráveis.</p><p>Com design, tecnologia e cuidado com os detalhes, criamos espaços onde seus convidados encontram tudo o que precisam — e sentem a energia do que está por vir.</p><a className="text-link" href="#servicos">Conheça as possibilidades <Arrow/></a></div></div><div className="values-row"><span>DETALHE EM CADA TELA</span><b>✳</b><span>DESIGN COM EMOÇÃO</span><b>✳</b><span>TECNOLOGIA SEM COMPLICAÇÃO</span></div></section>
<section id="projetos" className="projects section-space"><div className="container"><div className="section-heading"><div className="section-label light"><span>02</span><i/> CONVITES EM DESTAQUE</div><h2>Feitos para<br/><em>ser lembrados.</em></h2><p>Convites que criam expectativa antes mesmo de a celebração começar.</p></div><div className="project-grid">{projects.map((project,index)=><article className={`project-card ${project.className}`} key={project.name}><div className="project-art">{project.video&&<><video className="project-video" loop muted playsInline preload="none" controls aria-label={`Prévia do projeto ${project.name}`}><source src={project.video} type="video/mp4"/>Seu navegador não suporta vídeo HTML5.</video><div className="video-badge"><span>●</span> PROJETO REAL</div></>}{project.image&&<><Image className="project-preview" src={project.image} alt={`Prévia do conceito ${project.name}`} fill sizes="(max-width: 760px) calc(100vw - 32px), (max-width: 1200px) 50vw, 390px" quality={72} priority={index===1}/><div className="concept-badge">CONCEITO VISUAL</div></>}</div><div className="project-meta"><span>{project.number} — {project.category}</span><Arrow diagonal/></div><h3>{project.name}</h3><p>{project.detail}</p><a className="project-action" href={whatsappLink(`Olá, vim pelo site da K2 Tech e gostei do projeto ${project.name}. Gostaria de criar algo nesse estilo.`)} target="_blank" rel="noopener noreferrer">Quero algo assim <Arrow/></a></article>)}</div><div className="hero-actions"><Link className="button button-light all-projects" href="/projetos">Ver todos os projetos <Arrow/></Link><a className="button button-light all-projects" href={siteConfig.whatsappUrl} target="_blank" rel="noopener noreferrer">Crie seu convite com a K2 <Arrow/></a></div></div></section>
<ExperiencesSection/>
<section id="servicos" className="services container section-space"><div className="section-label"><span>04</span><i/> O QUE FAZEMOS</div><div className="services-head"><h2>Seu momento.<br/><em>Do seu jeito.</em></h2><p>Do convite à presença digital do seu negócio, construímos experiências que aproximam pessoas.</p></div><div className="service-list">{services.map(([number,title,text])=><article className="service-item" key={number}><span className="service-number">{number}</span><h3>{title}</h3><p>{text}</p><Arrow diagonal/></article>)}</div></section>
<section className="method section-space"><div className="container method-grid"><div><div className="section-label light"><span>05</span><i/> COMO FUNCIONA</div><h2>Boa parceria<br/>tem <em>processo.</em></h2></div><div className="steps"><article><span>01</span><div><h3>Seu momento</h3><p>Entendemos a história, o estilo e tudo o que os convidados precisam viver antes do evento.</p></div></article><article><span>02</span><div><h3>Direção criativa</h3><p>Transformamos a sua ideia em uma proposta visual única, feita para despertar expectativa.</p></div></article><article><span>03</span><div><h3>Convite no ar</h3><p>Construímos, refinamos e entregamos seu convite pronto para ser compartilhado com quem importa.</p></div></article></div></div></section>
<ContactSection/>
<footer className="footer"><div className="container footer-grid"><a className="brand footer-brand" href="#inicio"><K2Mark/></a><p>Convites e experiências digitais para momentos que merecem ser lembrados.</p><div className="footer-links"><a className="contact-link" href={siteConfig.whatsappUrl} target="_blank" rel="noopener noreferrer"><SiWhatsapp className="contact-icon whatsapp-icon" aria-hidden="true"/>WhatsApp · {siteConfig.phoneDisplay}</a><a className="contact-link" href={`mailto:${siteConfig.contactEmail}`}><SiGmail className="contact-icon gmail-icon" aria-hidden="true"/>{siteConfig.contactEmail}</a><a className="contact-link" href={siteConfig.instagramUrl} target="_blank" rel="noopener noreferrer"><SiInstagram className="contact-icon instagram-icon" aria-hidden="true"/>Instagram</a><Link href="/privacidade">Privacidade</Link></div><small>© {new Date().getFullYear()} K2 Tech. Todos os direitos reservados.</small><a className="back-top" href="#inicio">Voltar ao topo ↑</a></div></footer><a className="whatsapp-float" href={siteConfig.whatsappUrl} target="_blank" rel="noopener noreferrer" aria-label="Falar no WhatsApp"><SiWhatsapp className="contact-icon" aria-hidden="true"/><em>Falar no WhatsApp</em></a>
</main>}
